services:
  db:
    image: mongo
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=projet_f
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017

      