services:
  main:
    build: .
    command: python -u main.py
    ports:
      - '5000:5000'
    volumes:
      - .:/main
    links:
      - db
  db:
    image: mongo
    container_name: mongo
    hostname: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=projet_f
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017